package org.intermed.core.classloading;

import org.objectweb.asm.ClassWriter;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * ASM {@link ClassWriter} subclass that resolves common superclasses using a
 * pre-built {@link EulerTourRmq} LCA index instead of the default reflection
 * path (ТЗ 3.5.4).
 *
 * <h3>Why the default path is slow in large DAGs</h3>
 * ASM's {@code ClassWriter.getCommonSuperClass(type1, type2)} calls
 * {@code Class.forName()} on both types, then walks up each class's superclass
 * chain, doing an {@code isAssignableFrom} check on every step.  In a DAG with
 * 300+ mods this means:
 * <ul>
 *   <li>Recursive classloading (potentially triggering more codegen).</li>
 *   <li>O(d) superclass traversal for each pair, where d is the hierarchy
 *       depth — exponential when many dispatcher classes share ancestors.</li>
 * </ul>
 *
 * <h3>Solution</h3>
 * The {@link ClassHierarchyLcaIndex} is built once from all classes loaded by
 * the DAG at freeze time.  Each class gets a stable integer node ID.
 * {@link EulerTourRmq} answers LCA queries in O(1).  When a type is not in
 * the index (e.g. a freshly generated ByteBuddy class), we fall back to the
 * normal reflection-based resolution.
 *
 * <h3>Usage</h3>
 * Pass {@code ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS} and the
 * current {@link ClassHierarchyLcaIndex} to the constructor:
 * <pre>
 *   ClassWriter writer = new DagAwareClassWriter(
 *       ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS,
 *       ClassHierarchyLcaIndex.get());
 * </pre>
 */
public final class DagAwareClassWriter extends ClassWriter {

    private static final java.util.concurrent.atomic.AtomicLong LCA_QUERY_COUNT =
        new java.util.concurrent.atomic.AtomicLong();
    private static final java.util.concurrent.atomic.AtomicLong WRITER_CREATION_COUNT =
        new java.util.concurrent.atomic.AtomicLong();

    /** The LCA index to use, or null to always fall back to reflection. */
    private final ClassHierarchyLcaIndex lcaIndex;
    /** Cache: (internalType1 + "|" + internalType2) → common super internal name. */
    private final Map<String, String> cache = new ConcurrentHashMap<>();

    public DagAwareClassWriter(int flags, ClassHierarchyLcaIndex lcaIndex) {
        super(flags);
        this.lcaIndex = lcaIndex;
        WRITER_CREATION_COUNT.incrementAndGet();
    }

    /**
     * Returns a frame-computing writer backed by the active DAG LCA index when
     * frame computation is requested, or a plain ASM writer otherwise.
     */
    public static ClassWriter create(int flags) {
        if ((flags & ClassWriter.COMPUTE_FRAMES) != 0) {
            return new DagAwareClassWriter(flags, ClassHierarchyLcaIndex.get());
        }
        return new ClassWriter(flags);
    }

    public static long lcaQueryCount() {
        return LCA_QUERY_COUNT.get();
    }

    public static long writerCreationCount() {
        return WRITER_CREATION_COUNT.get();
    }

    static void resetDiagnosticsForTests() {
        LCA_QUERY_COUNT.set(0);
        WRITER_CREATION_COUNT.set(0);
    }

    @Override
    protected String getCommonSuperClass(String type1, String type2) {
        LCA_QUERY_COUNT.incrementAndGet();
        if (type1.equals(type2)) {
            return type1;
        }
        if (lcaIndex == null || !lcaIndex.isReady()) {
            return superclassViaReflection(type1, type2);
        }

        String cacheKey = type1.compareTo(type2) < 0
            ? type1 + "|" + type2
            : type2 + "|" + type1;

        return cache.computeIfAbsent(cacheKey, k -> resolveCommonSuper(type1, type2));
    }

    // ── Internal ──────────────────────────────────────────────────────────────

    private String resolveCommonSuper(String type1, String type2) {
        int id1 = lcaIndex.nodeIdForInternalName(type1);
        int id2 = lcaIndex.nodeIdForInternalName(type2);

        if (id1 < 0 || id2 < 0) {
            // At least one type is not in the index — fall back to reflection
            return superclassViaReflection(type1, type2);
        }

        int lcaId = lcaIndex.rmq().lca(id1, id2);
        if (lcaId < 0) {
            return superclassViaReflection(type1, type2);
        }

        String result = lcaIndex.internalNameForNodeId(lcaId);
        return result != null ? result : "java/lang/Object";
    }

    private String superclassViaReflection(String type1, String type2) {
        // Standard ASM reflection path — used as fallback for types outside the index
        try {
            Class<?> c1 = loadClassForName(type1);
            Class<?> c2 = loadClassForName(type2);
            if (c1 == null || c2 == null) return "java/lang/Object";
            if (c1.isAssignableFrom(c2)) return type1;
            if (c2.isAssignableFrom(c1)) return type2;
            if (c1.isInterface() || c2.isInterface()) return "java/lang/Object";
            do {
                c1 = c1.getSuperclass();
                if (c1 == null) return "java/lang/Object";
            } while (!c1.isAssignableFrom(c2));
            return c1.getName().replace('.', '/');
        } catch (Throwable t) {
            return "java/lang/Object";
        }
    }

    private Class<?> loadClassForName(String internalName) {
        String binaryName = internalName.replace('/', '.');
        try {
            ClassLoader tccl = Thread.currentThread().getContextClassLoader();
            return tccl != null ? Class.forName(binaryName, false, tccl)
                                : Class.forName(binaryName);
        } catch (ClassNotFoundException ignored) {
            return null;
        }
    }
}
